### PR TITLE
feature: connect login/sign up with backend

### PR DESCRIPTION
**Pull request by RuipuCui**
connect login/signup with postman server
add event that listen to the changes in login statue

### CODE REVIEW

**Review by YuetongLiiii — APPROVED** [review]
Good change. Make sure people can only access learning content if they haven't log in.

**Review by Leshangpang — APPROVED** [review]
Nice work. It is important to follow the client requirement that only home page and learning content page can be accessed before log in.

**Review by Wj12344 — APPROVED** [review]
Good job， thank you for your hard work ^_^

**Review by Leshangpang — APPROVED** [review]
Nice to see that the previous issues are now fixed.

**Pull request closed without merging**
