### PR TITLE
feature: create my question page

### PR DESCRIPTION
**Pull request by YuetongLiiii**
Here is the see users uploaded question page: my question in Question Hub. Please have a review.

### CODE REVIEW

**Review by Leshangpang — CHANGES_REQUESTED** [review]
I'm not sure if the background image for the banner is relevant. 1. It does not relate to the website's theme of the 17 SDGs. (focus on sustainable development goals) and 2. it kind of reduces the readability of the headings.

**Review by Wj12344 — APPROVED** [review]
This Vue component is a clean, well-structured banner that smartly utilizes props to dynamically display a background image, title, and subtitle. The design is responsive and flexible, with centered content and a beautiful overlay for better text visibility. The code is efficient, with thoughtful use of CSS to ensure the banner is visually appealing and easy to customize. Excellent work on simplicity and functionality! Also mentioned above，we should discuss the background picture tonight, and consider the style we want to use

**Review by Wj12344 — CHANGES_REQUESTED** [review]
About the image we use need further consider, and the function is good!

**Review by Wj12344 — APPROVED** [review]
background image is more suitable and  good structure of coding and layout of this page. thank you for your working ~_~

**Review by Leshangpang — APPROVED** [review]
Good job, this is looking really nice. Maybe some minor fixes in the future, but I think this is ready for merge.

**Pull request merged**
